### ISSUE TITLE
How do I use the content-based deduplication toggle?

### ISSUE THREAD

**Issue by douglasnaphas** [VerticalRelevance/control-broker-consumer-example-config#1]
@cschneider-vertical-relevance What is going on withe toggle that is read in [these lines](https://github.com/VerticalRelevance/control-broker-consumer-example-config/blob/e446633fbbee42fb39d15158adf5480f79037f5b/stacks/config_stack.py#L59-L65)?

```python
        # toggle content-based deduplication to trigger change tracked by Config
        
        toggled_boolean_path='./dev/tracked_by_config/toggled_boolean.json'
        
        # DEV: ToggledBoolean alternates upon every deploy
        with open(toggled_boolean_path,'r') as f:
            toggled_boolean = json.loads(f.read())['ToggledBoolean']
```

When I tried to deploy this stack, I got an error:

>  Traceback (most recent call last):
>   File "/home/runner/work/vr-sl-c/vr-sl-c/control-broker-consumer-example-config/app.py", line 12, in <module>
>     ControlBrokerConsumerExampleConfigStack(app, "CBConsumerConfig",
>   File "/opt/hostedtoolcache/Python/3.9.13/x64/lib/python3.9/site-packages/jsii/_runtime.py", line 86, in __call__
>     inst = super().__call__(*args, **kwargs)
>   File "/home/runner/work/vr-sl-c/vr-sl-c/control-broker-consumer-example-config/stacks/config_stack.py", line 51, in __init__
>     self.demo_change_tracked_by_config()
>   File "/home/runner/work/vr-sl-c/vr-sl-c/control-broker-consumer-example-config/stacks/config_stack.py", line 64, in demo_change_tracked_by_config
>     with open(toggled_boolean_path,'r') as f:
> FileNotFoundError: [Errno 2] No such file or directory: './dev/tracked_by_config/toggled_boolean.json'

What change do I need to make to get the stack to deploy? Do I need to add a file called `./dev/tracked_by_config/toggled_boolean.json` that either contains `{"ToggledBoolean": true}` or `{"ToggledBoolean": false}`? What are the consequences of each option? What is this option meant to accomplish?

**Comment by cschneider-vertical-relevance** [comment]
Yes, you need that file if you want to use this testing method. It's designed to be the event source that starts the downstream operations as you develop.

Totally optional if you have 'real-world' events that trigger the workflow instead.

gitignore is ignoring the file, which is why the deploy fails. Alternatively, we could track that file.

**Comment by cschneider-vertical-relevance** [comment]
https://github.com/VerticalRelevance/control-broker-consumer-example-config/blob/main/dev/tracked_by_config/toggled_boolean.json
